/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import jsonParser.Parser;
import org.example.controller.ICGFilter;

public class App {
    public static String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Parser configParser = new Parser();
        configParser.parse();

        ICGFilter filter = new ICGFilter(configParser.getFilterDtos(), configParser.getPathsToFilters(), configParser.getFilterNames());
        filter.start();
    }
}
